[package]
name = "cargo-profiler"
version = "0.1.0"
authors = ["sgururangan-r7 <sgururangan@rapid7.com>"]

[dependencies]
clap = "*"
regex = "*"
regex_macros = "*"
ndarray = "*"
lazy_static = "*"
[lib]
name="profiler"
lib="src/lib.rs"

[[bin]]
name = "cargo-profiler"
bin='src/main.rs'
